### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by ayoubkhan558** [loq24/wp-react-typescript#39]
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at noopServiceWorkerMiddleware (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:317:13)
    at D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:275:10)
    at launchEditorMiddleware (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:317:13)
    at D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:335:12)
    at next (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\index.js:275:10)
    at handleWebpackInternalMiddleware (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\Starterkits Boilerplates\Wordpress\new\wp-react-typescript-master\node_modules\express\lib\router\layer.js:95:5)

![image](https://user-images.githubusercontent.com/20210961/116818202-0ae44500-ab1f-11eb-8233-95f99222a018.png)

**Comment by ayoubkhan558** [comment]
#40

**Comment by loq24** [comment]
Hi @ayoubkhan558,

Just fixed a lot of problems and updated most of the dependencies. Tests files are also now fixed as well. Thank you.
